volumes:
  mysql_data:

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8084:80
    depends_on:
      - php-fpm

  php-fpm:
    container_name: fone_ninja_erp_api
    build: backend
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - /var/www/vendor
    depends_on:
      - mysql

  mysql:
    container_name: ms_mysql
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fone_ninja_erp
    ports:
      - 3319:3306

  frontend:
    container_name: fone_ninja_erp_app
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    depends_on:
      - nginx
